from .adult import load_and_preprocess_adult
from .compas import load_and_preprocess_compas
from .dropout import load_and_preprocess_dropout
from .intersectional_bias import load_and_preprocess_intersectional_bias
from .loaders_folktables import load_and_preprocess_folktables_income, load_and_preprocess_folktables_coverage
from .loaders_datasus import load_and_preprocess_sih, load_and_preprocess_sim, load_and_preprocess_sinasc
from .loaders_cadunico import load_and_preprocess_cadunico

import os
import pandas as pd
import streamlit as st

@st.cache_data
def load_local_parquet(file_name):
    """Lê um dataset pré-processado da pasta local data/processed/"""
    path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'data', 'processed', file_name))
    return pd.read_parquet(path)

# Dictionary mapping dataset names to their loader functions and relevant metadata
DATASETS = {
    'Adult 🇺🇸': {
        'loader': lambda: load_local_parquet('adult_processed.parquet'),
        'target': 'income',
        'favorable_val': 1,
        'target_mapping': {1: '> $50K', 0: '<= $50K'},
        'protected_attributes': ['sex', 'race', 'age_group'],
        'primary_protected': 'race',
        'privileged_group': 'White',
        'unprivileged_group': 'Black',
        'proxy_attributes': ['education_group', 'relationship'],
        'country_pt': '🇺🇸 Estados Unidos',
        'country_en': '🇺🇸 United States',
        'icon': '💰',
        'domain_pt': 'Renda',
        'domain_en': 'Income',
        'link': 'https://archive.ics.uci.edu/dataset/2/adult',
        'year': '1994',
        'original_n': 48842,
        'target_label_pt': 'Renda anual',
        'target_label_en': 'Annual income',
        'favorable_label_pt': 'Renda > $50K',
        'favorable_label_en': 'Income > $50K',
        'description_pt': "Avalia se a renda anual excede $50K.",
        'description_en': "Evaluates if annual income exceeds $50K."
    },
    # --- OCULTADOS PARA A PROPOSTA DE TESE (Serão ativados na Tese final) ---
    # 'ACSIncome (Folktables) 🇺🇸': {
    #     'loader': lambda: load_local_parquet('acsincome_processed.parquet'),
    #     'target': 'PINCP',
    #     'favorable_val': 1,
    #     'protected_attributes': ['SEX', 'RAC1P', 'AGEP_Group'],
    #     'proxy_attributes': ['SCHL'],
    #     'country': '🇺🇸 Estados Unidos',
    #     'icon': '💵',
    #     'domain': 'Censo Demográfico / Renda (ACS)',
    #     'link': 'https://github.com/socialfoundations/folktables',
    #     'year': '2018',
    #     'n_approx': '~370K (CA)',
    #     'target_label': 'Renda anual',
    #     'favorable_label': 'Renda > $50K',
    #     'description': "Substituto moderno do Adult, baseado no American Community Survey (ACS). Avalia se a renda anual excede $50K, com dados contemporâneos."
    # },
    # 'ACSPublicCoverage (Folktables) 🇺🇸': {
    #     'loader': lambda: load_local_parquet('acspubliccoverage_processed.parquet'),
    #     'target': 'PUBCOV',
    #     'favorable_val': 1,
    #     'protected_attributes': ['SEX', 'RAC1P', 'AGEP_Group'],
    #     'proxy_attributes': [],
    #     'country': '🇺🇸 Estados Unidos',
    #     'icon': '🏥',
    #     'domain': 'Saúde Pública / Cobertura',
    #     'link': 'https://github.com/socialfoundations/folktables',
    #     'year': '2018',
    #     'n_approx': '~370K (CA)',
    #     'target_label': 'Seguro de saúde público',
    #     'favorable_label': 'Possui cobertura',
    #     'description': "Prevê a probabilidade de um indivíduo possuir cobertura de seguro-saúde público, fortemente associado a determinantes sociais da saúde."
    # },
    # 'NIJ Recidivism 🇺🇸': {
    #     'loader': lambda: load_local_parquet('nij_processed.parquet'),
    #     'target': 'Recidivism_Arrest',
    #     'favorable_val': 0,
    #     'protected_attributes': ['Sex', 'Race', 'Age'],
    #     'proxy_attributes': [],
    #     'country': '🇺🇸 Estados Unidos',
    #     'icon': '🚔',
    #     'domain': 'Justiça Criminal',
    #     'link': 'https://nij.ojp.gov/funding/recidivism-forecasting-challenge',
    #     'year': '2021',
    #     'original_n': 25835,
    #     'target_label': 'Reincidência criminal',
    #     'favorable_label': 'Não reincidência',
    #     'description': "Prevê reincidência criminal ao longo de 1, 2 e 3 anos, com base em dados de indivíduos soltos na Geórgia (2013-2015)."
    # },
    # ------------------------------------------------------------------------
    'COMPAS 🇺🇸': {
        'loader': lambda: load_local_parquet('compas_processed.parquet'),
        'target': 'two_year_recid',
        'favorable_val': 0,  # Favorable is NOT recidivating
        'target_mapping': {0: 'Não Reincidente', 1: 'Reincidente'},
        'protected_attributes': ['sex', 'race', 'age_group'],
        'primary_protected': 'race',
        'privileged_group': 'Caucasian',
        'unprivileged_group': 'African-American',
        'di_target_val': 1, # Na Tabela do artigo, DI foi medido para a classe Reincidência (1) e deu 1.31
        'proxy_attributes': [],
        'country_pt': '🇺🇸 Estados Unidos',
        'country_en': '🇺🇸 United States',
        'icon': '⚖️',
        'domain_pt': 'Justiça Criminal',
        'domain_en': 'Criminal Justice',
        'link': 'https://github.com/propublica/compas-analysis',
        'year': '2016',
        'original_n': 7214,
        'target_label_pt': 'Reincidência criminal em 2 anos',
        'target_label_en': '2-year criminal recidivism',
        'favorable_label_pt': 'Não reincidência',
        'favorable_label_en': 'No recidivism',
        'description_pt': "Estima o risco de reincidência criminal em 2 anos. Atributos sensíveis incluem raça e sexo. O viés estrutural frequentemente superestima o risco para réus afro-americanos.",
        'description_en': "Estimates the risk of criminal recidivism in 2 years. Sensitive attributes include race and sex. Structural bias often overestimates risk for African-American defendants."
    },
    'Dropout 🇵🇹': {
        'loader': lambda: load_local_parquet('dropout_processed.parquet'),
        'target': 'Target',
        'favorable_val': 1,  # Graduate
        'target_mapping': {1: 'Formatura/Ativo', 0: 'Evasão'},
        'protected_attributes': ['Gender', 'Age_Group'],
        'primary_protected': 'Gender',
        'privileged_group': 'Female',
        'unprivileged_group': 'Male',
        'proxy_attributes': ['Mother_Qualification_Group', 'Debtor', 'Scholarship holder'],
        'country_pt': '🇵🇹 Portugal',
        'country_en': '🇵🇹 Portugal',
        'icon': '🎓',
        'domain_pt': 'Educação Superior',
        'domain_en': 'Higher Education',
        'link': 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
        'year': '2022',
        'original_n': 4424,
        'target_label_pt': 'Desfecho acadêmico',
        'target_label_en': 'Academic outcome',
        'favorable_label_pt': 'Formatura ou matrícula ativa',
        'favorable_label_en': 'Graduation or active enrollment',
        'description_pt': "Prevê a evasão ou formatura de estudantes universitários. Atributos sensíveis abrangem gênero, idade e qualificação dos pais. Curiosidade: mulheres apresentam taxas naturais de retenção significativamente maiores.",
        'description_en': "Predicts the dropout or graduation of university students. Sensitive attributes include gender, age, and parent's qualification. Fun fact: women have significantly higher natural retention rates."
    },
    'Intersectional Bias 🧪': {
        'loader': load_and_preprocess_intersectional_bias,
        'target': 'diagnosis',
        'favorable_val': 0,
        'target_mapping': {0: 'Saudável', 1: 'Diagnosticado'},
        'protected_attributes': ['race', 'sex'],
        'primary_protected': 'sex',
        'privileged_group': 'Male',
        'unprivileged_group': 'Female',
        'proxy_attributes': ['housing'],
        'country_pt': '🧪 Sem nacionalidade (simulado)',
        'country_en': '🧪 No nationality (simulated)',
        'icon': '🔬',
        'domain_pt': 'Saúde Mental (Benchmark Sintético)',
        'domain_en': 'Mental Health (Synthetic Benchmark)',
        'link': 'https://www.openml.org/search?type=data&sort=runs&id=44202&status=active',
        'year': '2022',
        'original_n': 10000,
        'target_label_pt': 'Diagnóstico clínico (esquizofrenia ou depressão)',
        'target_label_en': 'Clinical diagnosis (schizophrenia or depression)',
        'favorable_label_pt': '0 — Saudável (sem diagnóstico de doença mental)',
        'favorable_label_en': '0 — Healthy (no mental illness diagnosis)',
        'description_pt': "Partição de <b>treino</b> do benchmark sintético FAccT 2022 (10.000 instâncias). Desenvolvido para auditar classificadores de saúde mental com disparidades interseccionais ocultas entre raça e sexo.",
        'description_en': "<b>Training</b> partition of the FAccT 2022 synthetic benchmark (10,000 instances). Developed to audit mental health classifiers with hidden intersectional disparities between race and sex."
    },
    'SIH (DATASUS) 🇧🇷': {
        'loader': lambda uf='SP': load_and_preprocess_sih(uf),
        'supports_uf': True,
        'target': 'desfecho',
        'favorable_val': 'Alta',
        'protected_attributes': ['sexo', 'raca_cor'],
        'proxy_attributes': [],
        'country_pt': '🇧🇷 Brasil',
        'country_en': '🇧🇷 Brazil',
        'icon': '🏥',
        'domain_pt': 'Saúde Pública — Internações Hospitalares',
        'domain_en': 'Public Health — Hospital Admissions',
        'link': '',
        'year': '',
        'n_approx': '',
        'target_label_pt': 'Desfecho da internação hospitalar',
        'target_label_en': 'Hospital admission outcome',
        'favorable_label_pt': 'Alta hospitalar',
        'favorable_label_en': 'Hospital discharge',
        'description_pt': "Sistema de Informações Hospitalares. Avalia o desfecho da internação (Alta vs. Óbito). Revela disparidades na qualidade da assistência segundo raça/cor e sexo.",
        'description_en': "Hospital Information System. Evaluates admission outcome (Discharge vs. Death). Reveals disparities in care quality by race/color and sex."
    },
    'SIM (DATASUS) 🇧🇷': {
        'loader': lambda uf='SP': load_and_preprocess_sim(uf),
        'supports_uf': True,
        'target': 'tipo_obito',
        'favorable_val': 'Não Evitável',
        'protected_attributes': ['sexo', 'raca_cor'],
        'proxy_attributes': [],
        'country_pt': '🇧🇷 Brasil',
        'country_en': '🇧🇷 Brazil',
        'icon': '📋',
        'domain_pt': 'Saúde Pública — Mortalidade',
        'domain_en': 'Public Health — Mortality',
        'link': '',
        'year': '',
        'n_approx': '',
        'target_label_pt': 'Tipo de óbito',
        'target_label_en': 'Death type',
        'favorable_label_pt': 'Óbito não evitável pelo SUS',
        'favorable_label_en': 'Death not preventable by SUS',
        'description_pt': "Sistema de Informações sobre Mortalidade. Analisa se o óbito era evitável por intervenções do SUS. Exibe iniquidades de acesso e mortalidade precoce focada em raça/cor.",
        'description_en': "Mortality Information System. Analyzes if death was preventable by SUS interventions. Shows inequities in access and early mortality focused on race/color."
    },
    'SINASC (DATASUS) 🇧🇷': {
        'loader': lambda uf='SP': load_and_preprocess_sinasc(uf),
        'supports_uf': True,
        'target': 'desfecho_nascimento',
        'favorable_val': 'Normal',
        'protected_attributes': ['raca_cor_mae', 'idade_mae'],
        'proxy_attributes': ['escolaridade_mae'],
        'country_pt': '🇧🇷 Brasil',
        'country_en': '🇧🇷 Brazil',
        'icon': '👶',
        'domain_pt': 'Saúde Materno-Infantil',
        'domain_en': 'Maternal and Child Health',
        'link': '',
        'year': '',
        'n_approx': '',
        'target_label_pt': 'Desfecho do nascimento',
        'target_label_en': 'Birth outcome',
        'favorable_label_pt': 'Nascimento a termo, sem intercorrências',
        'favorable_label_en': 'Term birth, no complications',
        'description_pt': "Sistema de Informações sobre Nascidos Vivos. Foca em desfechos como prematuridade e baixo peso ao nascer, controlando determinantes sociais da mãe.",
        'description_en': "Live Births Information System. Focuses on outcomes like prematurity and low birth weight, controlling for mother's social determinants."
    },
    'CadÚnico 🇧🇷': {
        'loader': load_and_preprocess_cadunico,
        'target': 'pobreza_extrema',
        'favorable_val': 0,  # Not in extreme poverty
        'target_mapping': {0: 'Acima da Extrema Pobreza', 1: 'Extrema Pobreza'},
        'protected_attributes': ['raca_cor', 'sexo'],
        'proxy_attributes': ['escolaridade'],
        'country_pt': '🇧🇷 Brasil',
        'country_en': '🇧🇷 Brazil',
        'icon': '🤝',
        'domain_pt': 'Assistência Social',
        'domain_en': 'Social Assistance',
        'link': '',
        'year': '2012–2016',
        'n_approx': '',
        'target_label_pt': 'Condição de extrema pobreza',
        'target_label_en': 'Extreme poverty condition',
        'favorable_label_pt': 'Não está em extrema pobreza (renda > R$ 77,00/mês)',
        'favorable_label_en': 'Not in extreme poverty (income > R$ 77.00/month)',
        'description_pt': "Amostra do Cadastro Único. Avalia se a renda per capita familiar está abaixo da linha de extrema pobreza (R$ 77,00 na época). Fortemente marcado pelo racismo e sexismo estrutural.",
        'description_en': "Sample from the Unified Registry (CadÚnico). Evaluates if per capita family income is below the extreme poverty line (R$ 77.00 at the time). Heavily marked by structural racism and sexism."
    }
}
